generic_dict = {'generic_16Sm4Cm1402': ['RsmH_mono', 'RsmI_mono'],
                'generic_LYSINEaaRS': ['LysI_RS_dim',
                                       'LysII_RS_dim_mod_6:mg2'],
                'generic_Dus': ['DusA_mono', 'DusB_mono', 'DusC_mono'],
                'generic_RF': ['PrfA_mono', 'PrfB_mono'],
                'generic_Tuf': ['TufA_mono', 'TufB_mono'],
                'generic_RNase': ['RNase_T_dim_mod_4:mg2',
                                  'RNase_BN_dim_mod_2:zn2',
                                  'Rnd_mono_mod_5:mg2', 'Rnb_mono_mod_1:mg2',
                                  'Rph_mono_mod_mg2'],
                'generic_16s_rRNAs': ['RNA_b3851', 'RNA_b3968', 'RNA_b3756',
                                      'RNA_b3278', 'RNA_b4007', 'RNA_b2591',
                                      'RNA_b0201'],
                'generic_23s_rRNAs': ['RNA_b3854', 'RNA_b3970', 'RNA_b3758',
                                      'RNA_b3275', 'RNA_b4009', 'RNA_b2589',
                                      'RNA_b0204'],
                'generic_5s_rRNAs': ['RNA_b3855', 'RNA_b3971', 'RNA_b3759',
                                     'RNA_b3274', 'RNA_b4010', 'RNA_b2588',
                                     'RNA_b0205', 'RNA_b3272']}
