pathway = {'sec': {'enzymes': {'SecB_tetra': {'length_dependent': True,
                                              'fixed_keff': False},
                               'SecA_MONOMER': {'length_dependent': True,
                                                'fixed_keff': False},
                               'Sec-CPLX': {'length_dependent': True,
                                            'fixed_keff': False}},
                   'keff': 4.,
                   'length_dependent_energy': True,
                   'stoichiometry': {'atp_c': -1./25., 'adp_c': 1./25.,
                                     'pi_c': 1./25.}},

           'tat': {'enzymes': {'TatBC_octa': {'length_dependent': False,
                                              'fixed_keff': False},
                               'TatA_MONOMER': {'length_dependent': False,
                                                'fixed_keff': False}},
                   'keff': 0.0125,
                   'length_dependent_energy': False,
                   'stoichiometry': {}},

           'tat_alt': {'enzymes': {'TatBC_octa': {'length_dependent': False,
                                                  'fixed_keff': False},
                                   'TatE_MONOMER': {'length_dependent': False,
                                                    'fixed_keff': False}},
                       'keff': 0.0125,
                       'length_dependent_energy': False,
                       'stoichiometry': {}},

           'bam': {'enzymes': {'SurA_MONOMER': {'length_dependent': False,
                                                'fixed_keff': False},
                               'Bam-CPLX': {'length_dependent': False,
                                            'fixed_keff': False}},
                   'keff': 0.027,
                   'length_dependent_energy': False,
                   'stoichiometry': {}},

           'lol': {'enzymes': {'LolCDE-CPLX': {'length_dependent': False,
                                               'fixed_keff': False},
                               'LolA_MONOMER': {'length_dependent': False,
                                                'fixed_keff': False},
                               'LolB_MONOMER': {'length_dependent': False,
                                                'fixed_keff': False}},
                   'keff': 0.9,
                   'length_dependent_energy': False,
                   'stoichiometry': {'atp_c': -1., 'adp_c': 1., 'pi_c': 1.}},

           'yidC': {'enzymes': {'SRP-CPLX': {'length_dependent': True,
                                             'fixed_keff': False},
                                'YidC_MONOMER': {'length_dependent': True,
                                                 'fixed_keff': False}},
                    'keff': 20.,
                    'length_dependent_energy': False,
                    'stoichiometry': {'gtp_c': -1., 'gdp_c': 1., 'pi_c': 1.}},

           'secA': {'enzymes': {'SecA_MONOMER': {'length_dependent': True,
                                                 'fixed_keff': False}},
                    'keff': 4.,
                    'length_dependent_energy': True,
                    'stoichiometry': {'atp_c': -1./3./25., 'adp_c': 1./3./25.,
                                      'pi_c': 1./3./25.}},

           'srp_yidC': {'enzymes': {'SRP-CPLX': {'length_dependent': True,
                                                 'fixed_keff': False},
                                    'YidC_MONOMER': {'length_dependent': True,
                                                     'fixed_keff': False},
                                    'Sec-CPLX': {'length_dependent': True,
                                                 'fixed_keff': False}},
                        'keff': 20.,
                        'length_dependent_energy': False,
                        'stoichiometry': {'gtp_c': -1., 'gdp_c': 1.,
                                          'pi_c': 1.}},

           'srp': {'enzymes': {'SRP-CPLX': {'length_dependent': True,
                                            'fixed_keff': False},
                               'FtsY_MONOMER': {'length_dependent': False,
                                                'fixed_keff': True},
                               'Sec-CPLX': {'length_dependent': True,
                                            'fixed_keff': False}},
                   'keff': 20.,
                   'length_dependent_energy': False,
                   'stoichiometry': {'gtp_c': -2., 'gdp_c': 2., 'pi_c': 2.}}
           }
abbreviation_to_pathway = {'s': 'sec_translocation',
                           't': ['tat_translocation', 'tat_translocation_alt'],
                           'b': 'bam_translocation',
                           'l': 'lol_translocation',
                           'y': 'yidC_translocation',
                           'a': 'secA_translocation',
                           'p': 'srp_yidC_translocation',
                           'r': 'srp_translocation'}

# Some proteins require different numbers of a complex in order to be
# translocated by a pathways
multipliers = {'YidC_MONOMER': {'b1855': 2., 'b3731': 2.},
               'TatE_MONOMER': {'b4072': 20.0, 'b1475': 5.166666666666667,
                                'b1474': 5.166666666666667, 'b2817': 22.0,
                                'b0973': 14.0, 'b0972': 14.0, 'b0997': 13.5,
                                'b3893': 15.5, 'b0152': 21.0, 'b3894': 15.5,
                                'b1589': 14.0, 'b1588': 15.0, 'b2938': 6.25,
                                'b1587': 14.0, 'b1872': 26.0, 'b2997': 14.0,
                                'b2996': 21.0, 'b2994': 14.0, 'b2435': 20.0,
                                'b0894': 26.0, 'b0123': 23.0, 'b2206': 27.0,
                                'b2205': 20.0},
               'TatA_MONOMER': {'b4072': 20.0, 'b1475': 5.166666666666667,
                                'b1474': 5.166666666666667, 'b2817': 22.0,
                                'b0973': 14.0, 'b0972': 14.0, 'b0997': 13.5,
                                'b3893': 15.5, 'b0152': 21.0, 'b3894': 15.5,
                                'b1589': 14.0, 'b1588': 15.0, 'b2938': 6.25,
                                'b1587': 14.0, 'b1872': 26.0, 'b2997': 14.0,
                                'b2996': 21.0, 'b2994': 14.0, 'b2435': 20.0,
                                'b0894': 26.0, 'b0123': 23.0, 'b2206': 27.0,
                                'b2205': 20.0}}
